name: Notify Mega Repository

on:
  push:
    branches:
      - main

jobs:
  notify_mega_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Notify Mega Repository
        run: |
          const { Octokit } = require("octokit");
          const octokit = new Octokit({ auth: process.env.MEGA_REPO_TOKEN });

          octokit.repos.createDispatchEvent({
            owner: 'CMP315',
            repo: 'Project',
            event_type: 'update_from_api'
          });
        env:
          MEGA_REPO_TOKEN: ${{ secrets.MEGA_REPO_TOKEN }}
